const $=s=>document.querySelector(s);
async function api(path,options={}){const r=await fetch(path,options);if(r.status===401){location.href='/login';throw new Error('请先登录管理后台')}const text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch{throw new Error(text||`HTTP ${r.status}`)}if(!r.ok)throw new Error(data?.error?.message||`HTTP ${r.status}`);return data}
async function logoutAdmin(){try{await api('/api/admin/logout',{method:'POST'});location.href='/login'}catch(e){flash(e.message,true)}}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function flash(message,bad=false){const e=$('#flash');e.textContent=message;e.className=bad?'bad':'';e.style.display='block';setTimeout(()=>e.style.display='none',2600)}
function shortKey(v){return v.length>16?v.slice(0,9)+'…'+v.slice(-5):v}
document.querySelectorAll('.nav button').forEach(button=>button.onclick=()=>{document.querySelectorAll('.nav button,.page').forEach(e=>e.classList.remove('active'));button.classList.add('active');$('#page-'+button.dataset.page).classList.add('active');({accounts:loadAccountPage,apis:loadKeys,usage:loadUsage,ips:loadProxies}[button.dataset.page])()});

async function loadStatus(){const s=await api('/api/webui/status');$('#metrics').innerHTML=`<div class="metric"><b>${s.accounts}</b><span class="muted">CLI 账号实例</span></div><div class="metric"><b>${s.active_sessions}</b><span class="muted">30 分钟内可复用会话</span></div><div class="metric"><b>${s.api_keys}</b><span class="muted">API Keys</span></div><div class="metric"><b>${s.proxies}</b><span class="muted">IP 节点</span></div>`}
async function loadAccounts(){try{await loadStatus();const rows=await api('/api/webui/tokens');$('#accounts-body').innerHTML=rows.map(a=>{const cliState=a.active_requests>0?'处理中':a.cli_open?'已打开':'未启动',cliClass=a.active_requests>0||a.cli_open?'ok':'';const cliDetail=a.cli_open?`PID ${a.cli_pid} · ${a.cli_started_at?new Date(a.cli_started_at).toLocaleString():'—'}`:'按需启动';const admission=a.admission_cooldown_until&&new Date(a.admission_cooldown_until)>new Date()?`<br><span class="badge warn">准入冷却至 ${esc(new Date(a.admission_cooldown_until).toLocaleTimeString())}</span>`:'';return `<tr><td>${esc(a.label)}<br><span class="badge ${a.authenticated?'ok':'bad'}">${a.authenticated?'已登录':'未登录'}</span></td><td><span class="badge ${a.status==='运行中'?'ok':a.status==='待机'?'':'warn'}">${esc(a.status)}</span></td><td><span class="badge ${cliClass}">${cliState}</span><br><span class="muted">${esc(cliDetail)}</span></td><td>${a.current_exit?`<code>${esc(a.current_exit)}</code>`:'直连/系统网络'}</td><td>${a.active_sessions} / ${a.active_requests}</td><td>${a.models}</td><td class="muted">${esc(a.last_error||'—')}${admission}</td><td><button class="btn ${a.enabled?'gray':'blue'}" onclick='toggleAccount(${JSON.stringify(a.id)},${!a.enabled})'>${a.enabled?'停用':'启用'}</button> <button class="btn red" onclick='deleteAccount(${JSON.stringify(a.id)},${JSON.stringify(a.label)})'>移除</button></td></tr>`}).join('')}catch(e){flash(e.message,true)}}
let accountConfigLoaded=false;
function loadAccountPage(){loadAccounts();if(!accountConfigLoaded)loadAccountConfig()}
async function loadAccountConfig(force=false){if(accountConfigLoaded&&!force)return;try{const d=await api('/api/webui/accounts/config');$('#account-config-json').value=JSON.stringify(d,null,2);accountConfigLoaded=true;if(force)flash('账号配置已重新读取')}catch(e){flash(e.message,true)}}
function copyAccountConfig(){const value=$('#account-config-json').value;if(!value)return flash('没有可复制的配置',true);copyText(value)}
async function saveAccountConfig(){const text=$('#account-config-json').value.trim();if(!text)return flash('配置不能为空',true);try{JSON.parse(text)}catch{return flash('配置不是有效 JSON',true)}if(!confirm('配置包含完整登录凭据。确认保存并重载账号调度池？'))return;try{const d=await api('/api/webui/accounts/config',{method:'POST',headers:{'Content-Type':'application/json'},body:text});accountConfigLoaded=false;await loadAccounts();await loadAccountConfig();flash(`配置已保存：更新 ${d.updated}，新增 ${d.added}`)}catch(e){flash(e.message,true)}}
let loginTimer=null;
async function startAccountLogin(){try{const d=await api('/api/webui/accounts/login',{method:'POST'});const panel=$('#login-panel');panel.style.display='block';panel.innerHTML='<b>正在生成独立账号登录链接…</b><p class="muted">新账号凭据将保存到独立目录，不会覆盖已有账号。</p>';clearInterval(loginTimer);loginTimer=setInterval(()=>pollAccountLogin(d.id),1000)}catch(e){flash(e.message,true)}}
async function pollAccountLogin(id){try{const d=await api('/api/webui/accounts/login/status?id='+encodeURIComponent(id));const panel=$('#login-panel');if(d.url&&d.status==='waiting'){panel.innerHTML=`<b>登录链接已生成</b><p><a href="${esc(d.url)}" target="_blank" style="color:#58a6ff">点击这里在浏览器完成新账号登录</a></p><p class="muted">登录完成后本页会自动刷新。</p><button class="btn gray" onclick='cancelAccountLogin(${JSON.stringify(id)})'>取消登录</button>`}if(d.status==='completed'){clearInterval(loginTimer);panel.innerHTML='<span class="badge ok">账号登录成功</span>';await loadAccounts();flash('新账号已加入调度池')}else if(d.status==='failed'){clearInterval(loginTimer);panel.innerHTML=`<span class="badge bad">登录失败</span><p class="muted">${esc(d.error||'未知错误')}</p>`}else if(d.status==='cancelled'){clearInterval(loginTimer);panel.innerHTML='<span class="badge warn">登录已取消</span>'}}catch(e){clearInterval(loginTimer);flash(e.message,true)}}
async function cancelAccountLogin(id){try{await api('/api/webui/accounts/login/cancel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});clearInterval(loginTimer);$('#login-panel').innerHTML='<span class="badge warn">登录已取消</span>'}catch(e){flash(e.message,true)}}
async function toggleAccount(id,enabled){if(!confirm(enabled?'确认启用这个账号？':'确认停用这个账号？正在执行的请求不会被删除，但该账号将不再接收新任务。'))return;try{await api('/api/webui/accounts/toggle',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,enabled})});await loadAccounts();flash(enabled?'账号已启用':'账号已停用')}catch(e){flash(e.message,true)}}
async function deleteAccount(id,label){if(!confirm(`确认从网关移除账号「${label}」？\n将停止该账号 CLI、清理会话绑定，并从迁移配置移除。\n本机凭据文件不会被删除。`))return;try{await api('/api/webui/accounts/delete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});accountConfigLoaded=false;await loadAccounts();await loadAccountConfig();flash('账号已从网关移除；本机凭据文件仍被保留')}catch(e){flash(e.message,true)}}

async function copyText(value){try{if(window.isSecureContext&&navigator.clipboard?.writeText){await navigator.clipboard.writeText(value);flash('已复制');return}const area=document.createElement('textarea');area.value=value;area.setAttribute('readonly','');area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();area.setSelectionRange(0,area.value.length);const copied=document.execCommand('copy');area.remove();if(!copied)throw new Error('copy unavailable');flash('已复制')}catch{window.prompt('浏览器禁止自动复制，请手动复制：',value)}}
function copyBaseURL(){copyText($('#base-url').textContent)}
async function loadKeys(){try{const d=await api('/api/webui/apis');$('#keys-body').innerHTML=d.keys.map(k=>`<tr><td><code title="${esc(k)}">${esc(shortKey(k))}</code></td><td><button class="btn gray" onclick='copyText(${JSON.stringify(k)})'>复制</button> <button class="btn red" onclick='deleteKey(${JSON.stringify(k)})'>删除</button></td></tr>`).join('');await loadStatus()}catch(e){flash(e.message,true)}}
async function createKey(custom=false){try{const key=custom?$('#key-input').value.trim():'';const d=await api('/api/webui/apis/create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key})});$('#key-input').value='';await loadKeys();copyText(d.key);flash('Key 已创建并复制')}catch(e){flash(e.message,true)}}
async function deleteKey(key){if(!confirm('确认删除这个 API Key？'))return;try{await api('/api/webui/apis/delete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key})});await loadKeys();flash('已删除')}catch(e){flash(e.message,true)}}

function usageRows(value){return Object.entries(value).sort((a,b)=>b[1]-a[1]).map(([name,count])=>`<tr><td>${esc(shortKey(name))}</td><td>${Number(count).toLocaleString()}</td></tr>`).join('')}
async function loadUsage(){try{const d=await api('/api/webui/usage?days='+$('#usage-days').value);$('#usage-note').textContent=d.note;$('#usage-metrics').innerHTML=`<div class="metric"><b>${d.requests}</b><span class="muted">请求数</span></div><div class="metric"><b>${d.successful}</b><span class="muted">成功请求</span></div><div class="metric"><b>${d.requests?Math.round(d.successful/d.requests*100):0}%</b><span class="muted">成功率</span></div>`;$('#usage-model').innerHTML=usageRows(d.by_model);$('#usage-key').innerHTML=usageRows(d.by_key)}catch(e){flash(e.message,true)}}

let proxyItems=[],selectedProxy='';
function renderEgressTier(s={}){const tier=(s.tier||'unknown').toUpperCase(),cls=tier==='FULL'?'ok':tier==='LIMITED'?'warn':'bad',checked=s.checked_at?new Date(s.checked_at).toLocaleString():'尚未检测';$('#egress-tier').innerHTML=`<span class="badge ${cls}">${esc(tier)}</span> <span>${s.latency_ms||0} ms · ${esc(checked)} · ${esc(s.detail||'—')}</span>`}
function renderProxies(){const input=$('#proxy-input');if(document.activeElement!==input)input.value=proxyItems.map(x=>x.addr).join('\n');$('#proxy-body').innerHTML=proxyItems.map(p=>{const tier=(p.mode||'unknown').toUpperCase(),tierClass=tier==='FULL'?'ok':tier==='LIMITED'?'warn':'bad';return `<tr><td><code>${esc(p.addr)}</code>${p.addr===selectedProxy?' <span class="badge ok">当前</span>':''}</td><td>${esc(p.name||'—')}</td><td><span class="badge ${tierClass}">${esc(tier)}</span></td><td>${p.tier_checked_at?p.tier_latency_ms+' ms':'—'}</td><td>${p.last_checked&&p.detail?p.latency_ms+' ms':'—'}</td><td><span class="badge ${p.alive?'ok':'bad'}">${p.alive?'在线':'离线/未测'}</span></td><td class="muted">${esc(p.tier_detail||p.detail||'—')}</td><td><button class="btn ${p.alive?'blue':'gray'}" ${p.alive?'':'disabled'} onclick='selectProxy(${JSON.stringify(p.addr)})'>设为出口</button></td></tr>`}).join('')+(selectedProxy?`<tr><td colspan="8"><button class="btn gray" onclick="selectProxy('')">恢复直连/系统网络</button></td></tr>`:'')}
async function loadProxies(){try{const d=await api('/api/webui/proxy/pool');proxyItems=d.items||[];selectedProxy=d.selected||'';renderEgressTier(d.egress_tier);renderProxies()}catch(e){flash(e.message,true)}}
async function detectEgressTier(){try{flash('正在逐个检测 FULL 节点，请稍候');const d=await api('/api/webui/proxy/scan-full',{method:'POST'});proxyItems=d.items||[];selectedProxy=d.selected||'';renderEgressTier(d.egress_tier);renderProxies();await loadAccounts();flash(d.full_count?`检测完成：找到 ${d.full_count} 个 FULL 节点，已选择最低延迟出口`:'检测完成：未找到 FULL 节点',!d.full_count)}catch(e){flash(e.message,true)}}
async function saveProxies(){try{const items=$('#proxy-input').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);await api('/api/webui/proxy/pool',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items})});await loadProxies();await loadStatus();flash('IP 池已保存')}catch(e){flash(e.message,true)}}
async function detectProxies(){try{flash('正在检测，请稍候');const d=await api('/api/webui/proxy/refresh',{method:'POST'});proxyItems=d.items||[];renderProxies();flash('检测完成')}catch(e){flash(e.message,true)}}
async function selectProxy(addr){try{const d=await api('/api/webui/proxy/select',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({addr})});selectedProxy=addr;renderEgressTier(d.egress_tier);renderProxies();await loadAccounts();flash(addr?'出口已切换，CLI 子进程将在下次请求启动':'已恢复直连/系统网络')}catch(e){flash(e.message,true)}}

$('#base-url').textContent=location.protocol+'//'+location.hostname+':16882/v1';loadAccountPage();setInterval(()=>{if($('#page-accounts').classList.contains('active'))loadAccounts()},5000);
